### ISSUE TITLE
Provide installation instructions

### ISSUE THREAD

**Issue by luksak** [edisch/zenhub-harvest-tools#6]
I don't know how to install this. It would be useful to have some instructions.

**Comment by edisch** [comment]
Hey @luksak,

Great idea, I'll add some instructions to the README.md for anyone interested in using this.

**Comment by edisch** [comment]
@luksak I've added some installation instructions to the [README.md](https://github.com/edisch/zenhub-harvest-tools/blob/master/README.md). I'm going to close this issue.

**Comment by luksak** [comment]
Thank you!
